# Generated by automigrate — https://github.com/user/automigrate
#
# Source: python-selenium/before_test.py
# Framework: Selenium WebDriver (Python) → Playwright (Python)
# Key transformations:
#   - pytest + selenium fixture → playwright pytest plugin (page fixture)
#   - driver.get → page.goto
#   - driver.find_element(By.ID, x) → page.locator("#x")
#   - driver.find_element(By.NAME, x) → page.locator("[name='x']")
#   - driver.find_element(By.CSS_SELECTOR, x) → page.locator(x)
#   - element.send_keys("text") → locator.fill("text")
#   - element.send_keys(Keys.TAB) → locator.press("Tab")
#   - element.clear() → locator.clear()
#   - element.click() → locator.click()
#   - element.text → locator.text_content()
#   - element.get_attribute(x) → locator.get_attribute(x)
#   - element.is_displayed() → locator.is_visible()
#   - element.is_selected() → locator.is_checked()
#   - Select().select_by_visible_text → locator.select_option(label=x)
#   - file_input.send_keys(path) → locator.set_input_files(path)
#   - ActionChains.move_to_element → locator.hover()
#   - ActionChains.scroll_to_element → locator.scroll_into_view_if_needed()
#   - WebDriverWait + EC → Playwright auto-wait + expect() assertions
#   - driver.quit() → managed by playwright-pytest plugin

import re
from playwright.sync_api import Page, expect


def test_submit_valid_form(page: Page):
    """Fill in all fields and submit the contact form."""
    page.goto("https://demo-app.example.com/contact")
    expect(page.locator("form#contact-form")).to_be_visible()

    # Fill in name
    page.locator("#full-name").clear()
    page.locator("#full-name").fill("Alice Johnson")

    # Fill in email
    page.locator("#email").clear()
    page.locator("#email").fill("alice@example.com")

    # Fill in phone
    page.locator("[name='phone']").fill("555-0123")

    # Select subject from dropdown
    page.locator("#subject").select_option(label="Technical Support")

    # Select priority radio button
    page.locator("input[name='priority'][value='high']").click()

    # Fill in the message textarea
    page.locator("#message").fill(
        "I need help with my account settings.\n"
        "The notification preferences are not saving correctly."
    )

    # Check the terms agreement checkbox
    terms_checkbox = page.locator("#agree-terms")
    if not terms_checkbox.is_checked():
        terms_checkbox.click()
    expect(terms_checkbox).to_be_checked()

    # Upload an attachment
    page.locator("input[type='file']").set_input_files("/tmp/test-attachment.pdf")

    # Scroll to and click submit — Playwright auto-scrolls on click, but explicit for clarity
    submit_btn = page.locator("button[type='submit']")
    submit_btn.scroll_into_view_if_needed()
    submit_btn.click()

    # Wait for success page — auto-retrying URL assertion
    expect(page).to_have_url(re.compile(r"/contact/thank-you"))

    # Verify confirmation message
    expect(page.locator(".confirmation-message h2")).to_have_text(
        "Thank you for contacting us!"
    )

    # Verify ticket number is displayed
    ticket_number = page.locator(".ticket-number")
    expect(ticket_number).to_be_visible()
    expect(ticket_number).to_contain_text("Ticket #")


def test_client_side_validation(page: Page):
    """Verify form validation for required fields."""
    page.goto("https://demo-app.example.com/contact")
    expect(page.locator("form#contact-form")).to_be_visible()

    # Try submitting empty form
    page.locator("button[type='submit']").click()

    # Check that validation messages appear
    name_error = page.locator("#full-name + .error-text")
    expect(name_error).to_be_visible()
    expect(name_error).to_contain_text(re.compile(r"required", re.IGNORECASE))

    email_error = page.locator("#email + .error-text")
    expect(email_error).to_be_visible()

    # Fill in invalid email and verify format validation
    page.locator("#email").fill("not-an-email")
    page.locator("#email").press("Tab")

    # Playwright expect auto-retries until the text appears
    expect(page.locator("#email + .error-text")).to_contain_text(
        re.compile(r"valid email", re.IGNORECASE)
    )


def test_character_counter(page: Page):
    """Verify the character counter on the message field."""
    page.goto("https://demo-app.example.com/contact")
    expect(page.locator("form#contact-form")).to_be_visible()

    counter = page.locator(".char-counter")

    # Initially shows max characters
    expect(counter).to_contain_text("0 / 1000")

    # Type some text and verify counter updates — auto-retrying assertion
    page.locator("#message").fill("Hello, this is a test message.")
    expect(counter).to_contain_text("30 / 1000")


def test_form_reset(page: Page):
    """Verify the reset button clears all fields."""
    page.goto("https://demo-app.example.com/contact")
    expect(page.locator("form#contact-form")).to_be_visible()

    # Fill in some fields
    page.locator("#full-name").fill("Test User")
    page.locator("#email").fill("test@example.com")

    # Click reset
    page.locator("button[type='reset']").click()

    # Verify fields are cleared — auto-retrying value assertions
    expect(page.locator("#full-name")).to_have_value("")
    expect(page.locator("#email")).to_have_value("")


def test_hover_tooltip(page: Page):
    """Verify tooltip appears on hover."""
    page.goto("https://demo-app.example.com/contact")
    expect(page.locator("form#contact-form")).to_be_visible()

    # Hover over the help icon
    page.locator(".help-icon").hover()

    # Verify tooltip appears — Playwright auto-waits for visibility
    tooltip = page.locator(".tooltip-content")
    expect(tooltip).to_be_visible()
    expect(tooltip).to_contain_text("We typically respond within 24 hours")
