// Generated by automigrate — https://github.com/user/automigrate
//
// Source: puppeteer/before.test.js
// Framework: Puppeteer → Playwright (TypeScript)
// Key transformations:
//   - puppeteer.launch → Playwright test fixtures (no manual browser management)
//   - browser.newPage → test fixture provides page with isolated context
//   - page.setViewport → page.setViewportSize (or configure in playwright.config.ts)
//   - page.$(selector) → page.locator(selector) (lazy, no await)
//   - page.$$(selector) → page.locator(selector).all()
//   - page.$eval(sel, fn) → page.locator(sel).evaluate(fn) or textContent()
//   - page.$$eval(sel, fn) → page.locator(sel).evaluateAll(fn)
//   - page.type(sel, text) → page.locator(sel).pressSequentially(text) (key-by-key)
//   - page.click(sel) → page.locator(sel).click()
//   - page.select(sel, val) → page.locator(sel).selectOption(val)
//   - page.waitForSelector → page.locator(sel).waitFor() or auto-wait
//   - page.waitForNavigation → page.waitForLoadState or page.waitForURL
//   - page.waitForResponse → page.waitForResponse (same API)
//   - page.waitForTimeout → removed where possible (Playwright auto-waits)
//   - headless: 'new' → headless: true
//   - networkidle0/networkidle2 → 'networkidle'

import { test, expect } from '@playwright/test';

test.describe('Product Search and Filter', () => {
  test.beforeEach(async ({ page }) => {
    await page.setViewportSize({ width: 1280, height: 720 });
    await page.setExtraHTTPHeaders({
      'Accept-Language': 'en-US',
    });
  });

  test('should search products and display results', async ({ page }) => {
    await page.goto('https://demo-store.example.com', {
      waitUntil: 'networkidle',
    });

    // Type in the search box — pressSequentially mimics key-by-key typing
    await page.locator('#search-bar').pressSequentially('mechanical keyboard', { delay: 50 });

    // Click search button
    await page.locator('.search-submit-btn').click();

    // Wait for results to load
    await page.waitForLoadState('networkidle');
    const productItems = page.locator('.product-list .product-item');
    await productItems.first().waitFor();

    // Count results
    const resultCount = await productItems.count();
    expect(resultCount).toBeGreaterThan(0);

    // Verify search term is shown in the results header
    await expect(page.locator('.search-results-header h2')).toContainText('mechanical keyboard');

    // Verify each product card has required elements
    const firstProduct = page.locator('.product-item').first();
    const title = await firstProduct.locator('.product-title').textContent();
    const price = await firstProduct.locator('.product-price').textContent();
    const image = await firstProduct.locator('img.product-image').getAttribute('src');

    expect(title).toBeTruthy();
    expect(price).toMatch(/\$\d+\.\d{2}/);
    expect(image).toContain('https://');
  });

  test('should filter products by category and price range', async ({ page }) => {
    await page.goto('https://demo-store.example.com/products', {
      waitUntil: 'networkidle',
    });

    // Open filter sidebar
    await page.locator('[data-action="toggle-filters"]').click();
    await expect(page.locator('.filter-sidebar')).toBeVisible();

    // Select category filter
    await page.locator('.filter-category input[value="electronics"]').click();

    // Set price range
    const minPriceInput = page.locator('#price-min');
    await minPriceInput.click({ clickCount: 3 }); // select all text
    await minPriceInput.pressSequentially('25');

    const maxPriceInput = page.locator('#price-max');
    await maxPriceInput.click({ clickCount: 3 });
    await maxPriceInput.pressSequentially('150');

    // Apply filters
    const responsePromise = page.waitForResponse(
      (response) => response.url().includes('/api/products') && response.status() === 200,
    );
    await page.locator('button.apply-filters').click();
    await responsePromise;

    await page.locator('.product-item').first().waitFor();

    // Verify URL contains filter params
    expect(page.url()).toContain('category=electronics');
    expect(page.url()).toContain('price_min=25');

    // Verify result count badge updated
    await expect(page.locator('.results-count')).toHaveText(/\d+ results/);

    // Verify all displayed prices are within range
    const prices = await page
      .locator('.product-price')
      .evaluateAll((elements) =>
        elements.map((el) => parseFloat(el.textContent!.replace('$', ''))),
      );
    for (const price of prices) {
      expect(price).toBeGreaterThanOrEqual(25);
      expect(price).toBeLessThanOrEqual(150);
    }
  });

  test('should sort products and paginate', async ({ page }) => {
    await page.goto('https://demo-store.example.com/products', {
      waitUntil: 'networkidle',
    });

    await page.locator('.product-item').first().waitFor();

    // Select sort option
    await page.locator('#sort-select').selectOption('price-low-high');

    // Get prices and verify they are sorted ascending — no waitForTimeout needed
    // Playwright auto-waits for the sort to apply when we query the DOM
    const prices = await page
      .locator('.product-price')
      .evaluateAll((elements) =>
        elements.map((el) => parseFloat(el.textContent!.replace('$', ''))),
      );
    for (let i = 1; i < prices.length; i++) {
      expect(prices[i]).toBeGreaterThanOrEqual(prices[i - 1]);
    }

    // Navigate to page 2
    await page.locator('.pagination [data-page="2"]').click();
    await page.waitForLoadState('networkidle');

    // Verify we're on page 2
    await expect(page.locator('.pagination .active')).toHaveText('2');

    // Verify products are still displayed
    const pageItemCount = await page.locator('.product-item').count();
    expect(pageItemCount).toBeGreaterThan(0);

    // Take a screenshot of the second page
    await page.screenshot({
      path: 'screenshots/products-page-2.png',
      fullPage: true,
    });
  });

  test('should handle empty search results', async ({ page }) => {
    await page.goto('https://demo-store.example.com', {
      waitUntil: 'networkidle',
    });

    await page.locator('#search-bar').pressSequentially('xyznonexistentproduct123');
    await page.locator('.search-submit-btn').click();
    await page.waitForLoadState('networkidle');

    // Verify empty state
    await expect(page.locator('.no-results-container')).toBeVisible();
    await expect(page.locator('.no-results-container h3')).toContainText('No results found');

    // Verify suggested searches are shown
    const suggestions = page.locator('.suggested-search-link');
    const count = await suggestions.count();
    expect(count).toBeGreaterThan(0);
  });
});
