// Generated by automigrate — https://github.com/user/automigrate
//
// Source: selenium-js/before.test.js
// Framework: Selenium WebDriver (JavaScript) → Playwright (TypeScript)
// Key transformations:
//   - Builder/driver → Playwright test fixtures (page, context, browser)
//   - By.css/By.id/By.name → page.locator() with CSS selectors
//   - By.linkText → page.getByRole('link', { name })
//   - sendKeys → fill() for text, press() for special keys
//   - WebDriverWait + until → Playwright auto-wait + expect assertions
//   - driver.sleep → removed (Playwright auto-waits)
//   - Chai expect → Playwright expect with auto-retrying matchers
//   - switchTo().alert() → page.on('dialog') event handler
//   - driver.manage().deleteAllCookies() → context.clearCookies()

import { test, expect } from '@playwright/test';

test.describe('Shopping Cart', () => {
  test.beforeEach(async ({ context }) => {
    await context.clearCookies();
  });

  test('should add multiple items to cart and verify totals', async ({ page }) => {
    // Navigate to the store
    await page.goto('https://demo-store.example.com/products');
    await expect(page).toHaveTitle(/Products/);

    // Search for a product
    const searchInput = page.locator('[name="search"]');
    await searchInput.clear();
    await searchInput.fill('wireless headphones');
    await searchInput.press('Enter');

    // Wait for search results — Playwright auto-waits on locator actions
    const firstProduct = page.locator('.search-results .product-card').first();
    const productName = await firstProduct.locator('.product-title').textContent();
    const productPrice = await firstProduct.locator('.product-price').textContent();

    // Add first product to cart
    await firstProduct.locator('.add-to-cart-btn').click();

    // Wait for the toast notification
    await expect(page.locator('.toast-notification.success')).toBeVisible();

    // Navigate to another category and add a second item
    await page.getByRole('link', { name: 'Accessories' }).click();
    await expect(page).toHaveURL(/\/category\/accessories/);

    const secondProduct = page.locator('.product-card[data-category="accessories"]').first();
    await secondProduct.locator('.add-to-cart-btn').click();

    // Wait for cart badge to update — use auto-retrying assertion
    await expect(page.locator('.cart-badge')).toHaveText('2');

    // Open the cart
    await page.locator('#cart-icon').click();
    await expect(page.locator('.cart-drawer')).toBeVisible();

    // Verify cart contents
    const cartItems = page.locator('.cart-item');
    await expect(cartItems).toHaveCount(2);

    // Verify first item name is in cart
    await expect(cartItems.first().locator('.item-name')).toHaveText(productName!);

    // Update quantity of first item
    const quantityInput = cartItems.first().locator('input.quantity-input');
    await quantityInput.clear();
    await quantityInput.fill('3');
    await quantityInput.press('Tab');

    // Verify subtotal updated — no sleep needed, expect auto-retries
    const subtotal = await page.locator('.cart-subtotal .amount').textContent();
    expect(parseFloat(subtotal!.replace('$', ''))).toBeGreaterThan(0);

    // Apply a coupon code
    await page.locator('#coupon-code').fill('SAVE10');
    await page.locator('button.apply-coupon').click();

    // Wait for discount to appear — auto-retrying assertion
    await expect(page.locator('.discount-line .amount')).toContainText('-');

    // Proceed to checkout
    await page.locator('button.checkout-btn').click();
    await expect(page).toHaveURL(/\/checkout/);

    // Verify we landed on the checkout page
    await expect(page.locator('h1.checkout-title')).toHaveText('Checkout');

    // Verify order summary is visible
    await expect(page.locator('.order-summary')).toBeVisible();
  });

  test('should remove an item from cart', async ({ page }) => {
    await page.goto('https://demo-store.example.com/products');

    // Add a product — Playwright auto-waits for the button to be actionable
    await page.locator('.product-card:first-child .add-to-cart-btn').click();

    // Open cart
    await page.locator('#cart-icon').click();
    await expect(page.locator('.cart-drawer')).toBeVisible();

    // Set up dialog handler before triggering it
    page.on('dialog', async (dialog) => {
      await dialog.accept();
    });

    // Remove the item
    await page.locator('.cart-item .remove-btn').click();

    // Verify cart is empty
    await expect(page.locator('.empty-cart-message')).toContainText('Your cart is empty');
  });
});
