// Generated by automigrate — https://github.com/user/automigrate
//
// Source: cypress/before.cy.js
// Framework: Cypress → Playwright (TypeScript)
// Key transformations:
//   - describe/it → test.describe/test
//   - cy.visit → page.goto
//   - cy.get('[data-testid="x"]') → page.getByTestId('x')
//   - cy.get('[data-cy="x"]') → page.getByTestId('x') (configure testIdAttribute)
//   - cy.contains('text') → page.getByText('text')
//   - .type('text') → locator.fill('text')
//   - .type('{enter}') → locator.press('Enter')
//   - .clear() → locator.clear()
//   - .check()/.uncheck() → locator.check()/uncheck()
//   - .select(value) → locator.selectOption(value)
//   - .should('be.visible') → expect(locator).toBeVisible()
//   - .should('have.value', v) → expect(locator).toHaveValue(v)
//   - .should('have.text', t) → expect(locator).toHaveText(t)
//   - .should('contain.text', t) → expect(locator).toContainText(t)
//   - .should('have.class', c) → expect(locator).toHaveClass(RegExp)
//   - .should('have.attr', a, v) → expect(locator).toHaveAttribute(a, v)
//   - .should('be.checked') → expect(locator).toBeChecked()
//   - cy.intercept → page.route
//   - cy.wait('@alias') → await response promise
//   - .attachFile → locator.setInputFiles()
//   - cy.setCookie → context.addCookies
//   - cy.clearCookies → context.clearCookies
//   - cy.clearLocalStorage → page.evaluate(() => localStorage.clear())
//   - cy.reload → page.reload
//   - cy.url().should('include', x) → expect(page).toHaveURL(RegExp)
//   - cy.request → Playwright APIRequestContext

import { test, expect } from '@playwright/test';

test.describe('User Profile Settings', () => {
  test.beforeEach(async ({ page, context, request }) => {
    // Login via API to skip UI login flow
    const response = await request.post('/api/auth/login', {
      data: {
        email: 'test@example.com',
        password: 'Test1234!',
      },
    });
    const body = await response.json();
    await context.addCookies([
      { name: 'auth_token', value: body.token, url: 'https://demo-store.example.com' },
    ]);

    await page.goto('/settings/profile');
    await expect(page.getByTestId('profile-page')).toBeVisible();
  });

  test.afterEach(async ({ context, page }) => {
    await context.clearCookies();
    await page.evaluate(() => localStorage.clear());
  });

  test('should update display name and bio', async ({ page }) => {
    // Clear and update display name
    const displayNameInput = page.getByTestId('display-name-input');
    await expect(displayNameInput).toBeVisible();
    await displayNameInput.clear();
    await displayNameInput.fill('Jane Test User');

    // Update bio with multi-line text
    const bioTextarea = page.getByTestId('bio-textarea');
    await bioTextarea.clear();
    await bioTextarea.fill('QA Engineer\nAutomation enthusiast\nCoffee lover');

    // Select timezone from dropdown
    await page.locator('#timezone-select').selectOption('America/New_York');

    // Toggle email notifications (configure testIdAttribute for data-cy)
    const emailToggle = page.getByTestId('email-notifications-toggle');
    await expect(emailToggle).not.toBeChecked();
    await emailToggle.check();

    // Toggle dark mode
    await page.getByTestId('dark-mode-toggle').check();
    await expect(page.locator('body')).toHaveClass(/dark-theme/);

    // Save changes
    await page.getByTestId('save-profile-btn').click();

    // Verify success notification
    const notification = page.locator('.notification-banner');
    await expect(notification).toBeVisible();
    await expect(notification).toContainText('Profile updated successfully');

    // Reload and verify changes persisted
    await page.reload();
    await expect(page.getByTestId('display-name-input')).toHaveValue('Jane Test User');
    await expect(page.getByTestId('bio-textarea')).toContainText('QA Engineer');
    await expect(page.locator('#timezone-select')).toHaveValue('America/New_York');
    await expect(page.getByTestId('email-notifications-toggle')).toBeChecked();
  });

  test('should upload a profile avatar', async ({ page }) => {
    // Upload avatar image
    await page.locator('input[type="file"]#avatar-upload').setInputFiles('fixtures/avatar.png');

    // Wait for preview to appear
    const preview = page.getByTestId('avatar-preview');
    await expect(preview).toBeVisible();
    await expect(preview.locator('img')).toHaveAttribute('src', /blob:/);

    // Crop and confirm
    await page.getByTestId('crop-confirm-btn').click();

    // Verify the avatar updated
    const currentAvatar = page.getByTestId('current-avatar');
    const src = await currentAvatar.getAttribute('src');
    expect(src).not.toContain('default-avatar');

    // Verify success message
    await expect(page.getByText('Avatar updated')).toBeVisible();
  });

  test('should change password with validation', async ({ page }) => {
    await page.getByTestId('change-password-tab').click();

    // Enter mismatching passwords first
    await page.locator('#current-password').fill('Test1234!');
    await page.locator('#new-password').fill('NewPass123!');
    await page.locator('#confirm-password').fill('DifferentPass!');

    await page.getByTestId('update-password-btn').click();

    // Verify validation error
    await expect(page.locator('.error-message')).toBeVisible();
    await expect(page.locator('.error-message')).toHaveText('Passwords do not match');

    // Fix the confirmation password
    await page.locator('#confirm-password').clear();
    await page.locator('#confirm-password').fill('NewPass123!');

    await page.getByTestId('update-password-btn').click();

    // Verify success
    await expect(page).toHaveURL(/\/settings\/profile/);
    await expect(page.locator('.notification-banner')).toContainText('Password changed');
  });

  test('should handle network errors gracefully', async ({ page }) => {
    // Intercept the save API call and force a failure
    await page.route('**/api/user/profile', async (route) => {
      if (route.request().method() === 'PUT') {
        await route.fulfill({
          status: 500,
          contentType: 'application/json',
          body: JSON.stringify({ error: 'Internal Server Error' }),
        });
      } else {
        await route.continue();
      }
    });

    await page.getByTestId('display-name-input').clear();
    await page.getByTestId('display-name-input').fill('Updated Name');
    await page.getByTestId('save-profile-btn').click();

    // Verify error notification
    const errorBanner = page.locator('.notification-banner.error');
    await expect(errorBanner).toBeVisible();
    await expect(errorBanner).toContainText('Failed to save');

    // Verify form still has the user's input (not reset)
    await expect(page.getByTestId('display-name-input')).toHaveValue('Updated Name');
  });
});
