/**
 * Migration Guide Document Generator.
 * Generates a comprehensive MIGRATION_GUIDE.md from migration results.
 */

import type { MigrationReport, MigrationFileResult, SourceFramework } from '../../types/index.js';

export interface GuideOptions {
  sourceFramework: SourceFramework;
  sourceLanguage: string;
  targetLanguage: string;
  ciProvider?: string;
}

export function generateMigrationGuide(report: MigrationReport, options: GuideOptions): string {
  const sections: string[] = [];

  sections.push(generateHeader());
  sections.push(generateSummary(report, options));
  sections.push(generatePerFileNotes(report));
  sections.push(generateBeforeAfterExamples(report));
  sections.push(generateManualReviewSection(report));
  sections.push(generateRiskAreas(report));
  sections.push(generateRecommendedTestOrder(report));
  sections.push(generateBestPractices(options.sourceFramework));
  sections.push(generateCISetupGuide(options));
  sections.push(generateTrainingNotes(options.sourceFramework));

  return sections.join('\n\n');
}

function generateHeader(): string {
  return `# Migration Guide

> Generated by [automigrate](https://github.com/automigrate-tool/automigrate)
> Date: ${new Date().toISOString().split('T')[0]}`;
}

function generateSummary(report: MigrationReport, options: GuideOptions): string {
  const { summary } = report;
  const total = report.results.length;
  const succeeded = report.results.filter((r) => r.status === 'success').length;
  const failed = report.results.filter((r) => r.status === 'failed').length;
  const partial = report.results.filter((r) => r.status === 'partial').length;

  return `## 1. Summary

| Property | Value |
|----------|-------|
| Source Framework | ${options.sourceFramework} |
| Source Language | ${options.sourceLanguage} |
| Target Language | ${options.targetLanguage} |
| Total Files | ${total} |
| Fully Migrated | ${succeeded} |
| Partial Migration | ${partial} |
| Failed | ${failed} |
| Overall Confidence | ${summary?.overallConfidence ?? 'N/A'} |`;
}

function generatePerFileNotes(report: MigrationReport): string {
  const lines: string[] = [];
  lines.push('## 2. Per-File Migration Notes');
  lines.push('');
  lines.push('| Source File | Target File | Status | Confidence | Manual Interventions |');
  lines.push('|------------|-------------|--------|------------|---------------------|');

  for (const result of report.results) {
    const interventions = result.manualInterventions?.length ?? 0;
    const confidence = result.confidence ?? 'N/A';
    lines.push(
      `| \`${result.sourceFile}\` | \`${result.targetFile ?? 'N/A'}\` | ${result.status} | ${confidence} | ${interventions} |`,
    );
  }

  return lines.join('\n');
}

function generateBeforeAfterExamples(report: MigrationReport): string {
  const lines: string[] = [];
  lines.push('## 3. Before/After Examples');
  lines.push('');
  lines.push('The following are representative transformations from your codebase:');
  lines.push('');

  // Collect interventions that have before/after context
  const examples: { source: string; target: string; description: string }[] = [];
  for (const result of report.results) {
    if (result.manualInterventions) {
      for (const intervention of result.manualInterventions) {
        if (examples.length < 5) {
          examples.push({
            source: intervention.original ?? '// source code',
            target: intervention.suggestion ?? '// migrated code',
            description: intervention.message ?? intervention.type,
          });
        }
      }
    }
  }

  if (examples.length === 0) {
    lines.push('_No manual interventions recorded — all transforms were high-confidence._');
  }

  for (const [i, ex] of examples.entries()) {
    lines.push(`### Example ${i + 1}: ${ex.description}`);
    lines.push('');
    lines.push('**Before:**');
    lines.push('```');
    lines.push(ex.source);
    lines.push('```');
    lines.push('');
    lines.push('**After:**');
    lines.push('```');
    lines.push(ex.target);
    lines.push('```');
    lines.push('');
  }

  return lines.join('\n');
}

function generateManualReviewSection(report: MigrationReport): string {
  const lines: string[] = [];
  lines.push('## 4. Manual Review Required');
  lines.push('');

  const byCategory = new Map<string, { file: string; message: string }[]>();

  for (const result of report.results) {
    if (result.manualInterventions) {
      for (const intervention of result.manualInterventions) {
        const cat = intervention.type ?? 'general';
        if (!byCategory.has(cat)) byCategory.set(cat, []);
        byCategory.get(cat)!.push({
          file: result.sourceFile ?? result.sourcePath,
          message: intervention.message ?? intervention.description ?? 'Review needed',
        });
      }
    }
  }

  if (byCategory.size === 0) {
    lines.push('_No manual interventions needed._');
  }

  for (const [category, items] of byCategory) {
    lines.push(`### ${category}`);
    lines.push('');
    for (const item of items) {
      lines.push(`- **${item.file}**: ${item.message}`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

function generateRiskAreas(report: MigrationReport): string {
  const lines: string[] = [];
  lines.push('## 5. Risk Areas');
  lines.push('');
  lines.push('Files with complex patterns that need extra testing:');
  lines.push('');

  const riskyFiles = report.results.filter(
    (r) => (r.manualInterventions?.length ?? 0) > 2 || r.confidence === 'low',
  );

  if (riskyFiles.length === 0) {
    lines.push('_No high-risk files identified._');
  }

  for (const file of riskyFiles) {
    lines.push(
      `- **\`${file.sourceFile}\`** — ${file.manualInterventions?.length ?? 0} manual interventions, confidence: ${file.confidence ?? 'N/A'}`,
    );
  }

  return lines.join('\n');
}

function generateRecommendedTestOrder(report: MigrationReport): string {
  const lines: string[] = [];
  lines.push('## 6. Recommended Test Validation Order');
  lines.push('');
  lines.push('Start with the simplest files (highest confidence) and work toward complex ones:');
  lines.push('');

  const sorted = [...report.results]
    .filter((r) => r.status !== 'failed')
    .sort((a, b) => {
      const confOrder = { high: 0, medium: 1, low: 2 };
      const aConf = confOrder[a.confidence as keyof typeof confOrder] ?? 1;
      const bConf = confOrder[b.confidence as keyof typeof confOrder] ?? 1;
      return aConf - bConf;
    });

  for (const [i, file] of sorted.entries()) {
    lines.push(
      `${i + 1}. \`${file.targetFile ?? file.sourceFile}\` (${file.confidence ?? 'medium'} confidence)`,
    );
  }

  return lines.join('\n');
}

function generateBestPractices(sourceFramework: SourceFramework): string {
  return `## 7. Playwright Best Practices

### Auto-Wait
Playwright auto-waits for elements before performing actions. You rarely need explicit waits.
${sourceFramework === 'selenium' ? "Unlike Selenium, you don't need `WebDriverWait` or `ExpectedConditions` for most cases." : ''}
${sourceFramework === 'cypress' ? "Unlike Cypress's built-in retry mechanism, Playwright's auto-wait is built into every action." : ''}

### Locator Strategies
Prefer semantic locators in this order:
1. \`page.getByRole()\` — accessible roles
2. \`page.getByText()\` — visible text
3. \`page.getByTestId()\` — test IDs
4. \`page.getByLabel()\` — form labels
5. \`page.locator()\` — CSS/XPath (last resort)

### Test Isolation
Each test runs in its own \`BrowserContext\`, providing complete isolation (cookies, storage, etc.).

### Parallel Execution
Playwright runs test files in parallel by default. Use \`test.describe.serial()\` only when tests must run sequentially.

### Fixtures
Use Playwright's built-in fixtures (\`page\`, \`context\`, \`browser\`) and extend them with \`test.extend()\` for custom setups.

### Page Object Model
Create page objects that accept a \`Page\` instance and expose locators as properties and actions as methods.`;
}

function generateCISetupGuide(options: GuideOptions): string {
  const lines: string[] = [];
  lines.push('## 8. CI Setup Guide');
  lines.push('');
  lines.push('### Quick Start');
  lines.push('');

  if (options.targetLanguage === 'python') {
    lines.push('```bash');
    lines.push('pip install -r requirements.txt');
    lines.push('playwright install --with-deps chromium');
    lines.push('pytest --browser chromium');
    lines.push('```');
  } else {
    lines.push('```bash');
    lines.push('npm ci');
    lines.push('npx playwright install --with-deps');
    lines.push('npx playwright test');
    lines.push('```');
  }

  lines.push('');
  lines.push('### Artifacts');
  lines.push('Configure your CI to upload these directories after test runs:');
  lines.push('- `playwright-report/` — HTML report');
  lines.push('- `test-results/` — Traces, screenshots, and videos for failed tests');

  if (options.ciProvider) {
    lines.push('');
    lines.push(`A ${options.ciProvider} pipeline config has been generated automatically.`);
  }

  return lines.join('\n');
}

function generateTrainingNotes(sourceFramework: SourceFramework): string {
  const notes: Record<string, string[]> = {
    selenium: [
      'Playwright auto-waits — remove explicit `WebDriverWait` calls',
      'Use `page.locator()` instead of `driver.findElement()`',
      'Browser lifecycle is managed by the test runner, not your code',
      '`expect(locator)` assertions auto-retry, unlike `Assert.assertEquals()`',
    ],
    cypress: [
      'Playwright uses `async/await` — no automatic command chaining',
      '`page.goto()` replaces `cy.visit()`',
      '`page.route()` replaces `cy.intercept()`',
      "Use `await expect(locator).toBeVisible()` instead of `.should('be.visible')`",
    ],
    puppeteer: [
      'Use `page.locator()` instead of `page.$()`',
      '`page.locator().fill()` replaces `page.type()`',
      "Playwright's `expect` assertions are built-in (no separate assertion library needed)",
    ],
    webdriverio: [
      'Playwright uses `page.locator()` instead of `$()` and `$$()`',
      'Use `page.locator().fill()` instead of `setValue()`',
      'Browser and page are managed by the test runner via fixtures',
    ],
    appium: [
      'Playwright is primarily for web testing — mobile-native tests may need alternative solutions',
      'Web views can be tested directly without context switching',
      'Use `page.setViewportSize()` for responsive testing',
    ],
    robot: [
      'Playwright tests are written in Python/JS/TS, not keyword-driven',
      "Use pytest fixtures instead of Robot Framework's variable system",
      "Playwright's auto-wait replaces explicit `Wait Until` keywords",
    ],
  };

  const tips = notes[sourceFramework] ?? notes.selenium;

  return `## 9. Team Training Notes

### Key Differences from ${sourceFramework}

${tips.map((t) => `- ${t}`).join('\n')}

### Recommended Resources

- [Playwright Documentation](https://playwright.dev/)
- [Playwright Best Practices](https://playwright.dev/docs/best-practices)
- [Playwright Test Generator](https://playwright.dev/docs/codegen) — record tests interactively
- [Playwright Trace Viewer](https://playwright.dev/docs/trace-viewer) — debug failing tests visually`;
}
