// Generated by automigrate — https://github.com/user/automigrate
//
// Source: selenium-java/before/ShoppingCartTest.java
// Framework: Selenium WebDriver (Java) → Playwright (Java)
// Key transformations:
//   - WebDriver/ChromeDriver → Playwright Page (test fixture managed)
//   - By.id/By.cssSelector/By.className → page.locator() with CSS
//   - By.linkText → page.getByRole(AriaRole.LINK, ...)
//   - By.name → page.locator("[name=...]")
//   - findElement/findElements → locator() (lazy, no await on creation)
//   - WebDriverWait + ExpectedConditions → Playwright auto-wait + assertThat
//   - Actions.moveToElement → locator.hover()
//   - Actions.scrollToElement → locator.scrollIntoViewIfNeeded()
//   - Select dropdown → locator.selectOption()
//   - sendKeys → fill() for text, press() for special keys
//   - isDisplayed → isVisible / assertThat().isVisible()
//   - isSelected → isChecked / assertThat().isChecked()
//   - JUnit assertions → Playwright assertThat (auto-retrying)
//   - TakesScreenshot → page.screenshot()

package com.example.tests;

import com.microsoft.playwright.*;
import com.microsoft.playwright.options.AriaRole;
import org.junit.jupiter.api.*;

import java.nio.file.Paths;

import static com.microsoft.playwright.assertions.PlaywrightAssertions.assertThat;

@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
public class ShoppingCartTest {

    private static Playwright playwright;
    private static Browser browser;
    private BrowserContext context;
    private Page page;

    @BeforeAll
    static void launchBrowser() {
        playwright = Playwright.create();
        browser = playwright.chromium().launch(
            new BrowserType.LaunchOptions().setHeadless(true)
        );
    }

    @AfterAll
    static void closeBrowser() {
        browser.close();
        playwright.close();
    }

    @BeforeEach
    void createContext() {
        context = browser.newContext(
            new Browser.NewContextOptions()
                .setViewportSize(1920, 1080)
        );
        page = context.newPage();
    }

    @AfterEach
    void closeContext() {
        context.close();
    }

    @Test
    @Order(1)
    void testAddItemsToCart() {
        // Navigate to the store
        page.navigate("https://demo-store.example.com/products");
        assertThat(page).hasTitle("Products | Demo Store");

        // Search for a product
        Locator searchBox = page.locator("#search-input");
        searchBox.clear();
        searchBox.fill("laptop stand");
        searchBox.press("Enter");

        // Playwright auto-waits — no explicit wait needed
        Locator products = page.locator(".product-grid .product-card");
        assertThat(products.first()).toBeVisible();

        // Get product details before adding
        int productCount = products.count();
        assert productCount > 0 : "Search should return results";

        Locator firstProduct = products.first();
        String productTitle = firstProduct.locator(".product-name").textContent();

        // Hover to reveal quick-add button
        firstProduct.hover();

        // Click add to cart — Playwright auto-waits for actionability
        firstProduct.locator(".quick-add-btn").click();

        // Verify confirmation toast
        assertThat(page.locator(".toast-message")).containsText("added to cart");

        // Select quantity using dropdown
        page.locator("#mini-cart-qty").selectOption(new SelectOption().setLabel("3"));

        // Navigate to cart page
        page.getByRole(AriaRole.LINK, new Page.GetByRoleOptions().setName("View Cart")).click();
        assertThat(page).hasURL(java.util.regex.Pattern.compile("/cart"));

        // Verify the item is in the cart
        Locator cartItem = page.locator(".cart-table .cart-row");
        assertThat(cartItem).toBeVisible();
        assertThat(cartItem.locator(".item-name")).hasText(productTitle);

        // Verify quantity
        assertThat(cartItem.locator("input[name='quantity']")).hasValue("3");

        // Take a screenshot for verification
        page.screenshot(new Page.ScreenshotOptions()
            .setPath(Paths.get("screenshots/cart-items.png")));
    }

    @Test
    @Order(2)
    void testApplyCouponAndCheckout() {
        page.navigate("https://demo-store.example.com/cart");
        assertThat(page.locator(".cart-table")).toBeVisible();

        // Apply a coupon
        page.locator("[name='coupon']").fill("WELCOME20");
        page.locator("button.apply-coupon-btn").click();

        // Verify discount — Playwright auto-retries assertions
        Locator discountAmount = page.locator(".discount-row .amount");
        assertThat(discountAmount).toBeVisible();
        assertThat(discountAmount).containsText("-$");

        // Verify total is updated
        assertThat(page.locator(".order-total .total-amount")).not().toBeEmpty();

        // Scroll to checkout button and click
        Locator checkoutBtn = page.locator("#proceed-to-checkout");
        checkoutBtn.scrollIntoViewIfNeeded();
        checkoutBtn.click();

        // Verify we're on checkout page
        assertThat(page).hasURL(java.util.regex.Pattern.compile("/checkout"));
        assertThat(page.locator("h1")).hasText("Checkout");

        // Fill shipping address
        page.locator("#first-name").fill("Jane");
        page.locator("#last-name").fill("Doe");
        page.locator("#address-line1").fill("123 Test Street");
        page.locator("#city").fill("Testville");

        // Select state from dropdown
        page.locator("#state").selectOption("CA");

        page.locator("#zip-code").fill("90210");

        // Select shipping method
        page.locator("input[value='express']").click();

        // Verify shipping method is selected
        assertThat(page.locator("input[value='express']")).toBeChecked();

        // Verify order summary section exists
        assertThat(page.locator(".checkout-summary")).toBeVisible();
    }
}
